version: "3.7"

services:
  web:
    build: ./app
    command: gunicorn --env DJANGO_SETTINGS_MODULE=config.settings.production config.wsgi:application --bind 0.0.0.0:8765
    env_file: ./env/prod/.env
    ports:
      - 8007:8765
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: ./env/prod/.env
volumes:
  postgres_data:
  static_volume:
  media_volume:
